i386:
	./bld.sh i386 i386-linux

x86_64:
	./bld.sh x86_64 x86_64-linux

arm:
	./bld.sh arm arm-linux-gnueabi

aarch64:
	./bld.sh aarch64 aarch64-linux

mips:
	./bld.sh mips mips-linux

clean:
	rm -rf build

distclean: clean
	rm -rf toolchains
